### ISSUE TITLE
How to make sense of math derivation in paper

### ISSUE THREAD

**Issue by litianyu93** [onolab-tmu/AuxTDE#1]
In paper "Estimation of Consistent Time Delays in Subsample via Auxiliary-Function-Based Iterative Updates", formula(14)&(15) is derived by substituting formula(11) to (6). The formula(15) has two items of RTF "g_k" but the variable is "a", not "a_k". In other words, "a_k" lost its subscript.
1.What does this "a" mean?
2.What is the difference between "a" and "a_k"?

Thanks for your answers!

**Comment by KoueiYamaoka** [comment]
Sorry, I made mistakes. All the "a"s in (15) are actually "a_k".

Thank you for letting me know!

**Comment by litianyu93** [comment]
You are welcome.
Ok, I got it.
But I derive the formula from (15) to (18), and I found a different result, maybe I'm wrong, or there is some mistake in your derivation, I've send you an e-mail, please check it!
Looking forward to receiving your reply!
